<a href="https://colab.research.google.com/github/tkdforever18/Carlos/blob/main/Carlos_Study.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Carlos Study - 05-02-2023**

In [96]:
L = list(range(14))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]

In [97]:
type(L)

list

In [98]:
type(L[0])

int

In [99]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13']

In [100]:
type(L2[0])

str

In [101]:
L3 = [True, 3, 2.1, "Carlos"]
L3

[True, 3, 2.1, 'Carlos']

In [102]:
[type(item) for item in L3]

[bool, int, float, str]

In [103]:
import array as ay

In [104]:
L = list(range(10))
A = ay.array('i',L)  # type of code que indica que el contenido de la lista es 'i' = 'integer'
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# **Es más eficiente utilizar ndarray, a pesar que array de phyton es eficiente, NumPy contiene operaciones de datos más eficientes aún.**


In [105]:
import numpy as np

In [106]:
# integer array:
np.array([1,3,5,2,4,6])   # A diferencia de Phyton array, NumPy array toda la lista debe ser del mismo tipo "eg. todos integer, eg. todos string"

array([1, 3, 5, 2, 4, 6])

In [107]:
# en caso de que los valores de la lista no sean del mismo tipo, NumPy intentará convertir todos si es posible (eg. floating > Integer)
np.array([3.1416, 6 , 9 , 12])

array([ 3.1416,  6.    ,  9.    , 12.    ])

In [108]:
# Si queremos cambiar el tipo de dato en una lista simplemente lo escribimos de la siguiente forma
np.array([1,3,5,7,2,4,6], dtype='float64')

array([1., 3., 5., 7., 2., 4., 6.])

In [109]:
np.array([1,3,5,7,2,4,6], dtype='str')

array(['1', '3', '5', '7', '2', '4', '6'], dtype='<U1')

In [110]:
# Matriz en NumPy como multidimensionales, ésta es una forma de como se puede realizar.
# The in list , cada numero es un renglón, logrando una matriz de dos dimensiones.
np.array([range(i,i+3) for i in [2,4,6,8,10,12,14]])

array([[ 2,  3,  4],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 8,  9, 10],
       [10, 11, 12],
       [12, 13, 14],
       [14, 15, 16]])

In [111]:
#Crear Listas desde ceros.
#Crear una lista de 10 datos, todos ceros.
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [112]:
#Crear una matriz de 3x5 de puros 1, con floating decimals.
np.ones((3,5), dtype = float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [113]:
#Crear una matriz de 3x5 de puros 3.1416
np.full((3,5) , 3.1416)

array([[3.1416, 3.1416, 3.1416, 3.1416, 3.1416],
       [3.1416, 3.1416, 3.1416, 3.1416, 3.1416],
       [3.1416, 3.1416, 3.1416, 3.1416, 3.1416]])

In [114]:
#Crear un array con una secuencia linear, empezando de 0 y terminando en 20, de dos en dos.
# Es una función similar a built-in range() function)
np.arange(0 ,20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [115]:
# Crear un array de 5 con espacios separados perefectamente entre el 0 y 1
np.linspace(0 , 1 , 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [116]:
np.linspace(1 , 20, 20, dtype = int)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [117]:
np.linspace ( 1 , 20 , 20, dtype = 'str')

array(['1.0', '2.0', '3.0', '4.0', '5.0', '6.0', '7.0', '8.0', '9.0',
       '10.0', '11.0', '12.0', '13.0', '14.0', '15.0', '16.0', '17.0',
       '18.0', '19.0', '20.0'], dtype='<U32')

In [118]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3 , 3))

array([[0.34507985, 0.91095479, 0.48227527],
       [0.35348353, 0.17968589, 0.11581016],
       [0.83819767, 0.6444566 , 0.4083741 ]])

In [119]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[-1.0631478 , -1.21772979, -0.65686179],
       [-0.80345968, -0.17947411,  0.37225046],
       [-0.29312967,  0.97150941,  0.84550733]])

In [120]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[2, 9, 8],
       [4, 8, 4],
       [6, 1, 6]])

In [121]:
np.random.randint(0 , 10, (6,6))

array([[6, 8, 8, 5, 0, 4],
       [5, 7, 8, 3, 5, 8],
       [2, 7, 5, 4, 1, 4],
       [4, 3, 3, 7, 8, 4],
       [1, 4, 9, 7, 8, 9],
       [2, 5, 9, 4, 6, 3]])

In [122]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [123]:
# Create a 6x6 identity matrix
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [124]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
np.empty(3)

array([1., 1., 1.])

In [125]:
import numpy as np
import pandas as pd

In [126]:
a = np.array([0,1,2,3,4,5,6,7,8,9,10])
np.mean(a)


5.0

In [127]:
type(a)

numpy.ndarray

In [128]:
a = complex(2,3)
b = 3 + 4j
c = np.dot(a, b) #2*3 - 12 + 9j + 8j = -6+17j

In [129]:
print('a\t : ', a )  #\t = tabulador, para dar espacio de tab al texto entre comillado
print('b\t : ', b )
print('c :',c)

a	 :  (2+3j)
b	 :  (3+4j)
c : (-6+17j)


In [130]:
type(a)

complex

In [131]:
d = np.dot(3j,4j)
d

(-12+0j)

In [132]:
x = 2 + 3j
y = 4 + 5j
np.dot(x,y)   #(2 + 3j)* (4 + 5j) = 8 - 15 + 10j + 12j = -7 + 22j

(-7+22j)

In [133]:
import pandas as pd

In [134]:
datafile = "https://raw.githubusercontent.com/tkdforever18/Carlos/main/Datasets-main/datasets/Cartwheeldata.csv?token=GHSAT0AAAAAAB5NVLASO6HGFQZ4M3FTQVQAY7FGDPQ"
df = pd.read_csv(datafile)
df.head(2)

HTTPError: ignored

In [ ]:
type(df)

In [ ]:
print(*df.columns,
      sep = '\n') #'\n'te da las columnas en una lista hacia abajo.

In [ ]:
df.columns

In [ ]:
for i in df.columns:
  print (i)

In [ ]:
c_namesA = df.columns
print(*c_namesA,
      sep = '\n')

In [ ]:
c_namesA = df.columns
print(*c_namesA,
      sep = ', ')

In [ ]:
c_namesB = list(df.columns)
c_namesB.sort()
print(*c_namesB, sep = '; ')     #The column names saved in a variable c_namesB, sorted alphabetically, then it is separated by ; on printing.

In [ ]:
res = "\n".join("{} \t\t {}".format(x,y) for x, y in zip(c_namesB,c_namesA))
print(res)

In [ ]:
type(res)


.loc()
df.loc[row_start : row_end, column_start:column_end]

In [ ]:
df.columns

In [ ]:
df.loc[:,'CWDistance']


In [ ]:
df.iloc[:,8]

In [ ]:
df.iloc[:,-4:]

In [ ]:
df.columns

In [ ]:
df.iloc[ : , :4]

In [ ]:
df.columns

In [ ]:
df.iloc[:5 , -4:-2]

In [ ]:
df.columns

In [ ]:
df.loc[ 0:5 , ['ID','Glasses', 'CWDistance' , 'Score']]

In [ ]:
# Select range of rows for all columns
df.loc[5:10]

In [ ]:
#The .loc() function requires two arguments, the indices of the rows and the column names you wish to observe.
#In the above case : specifies all rows, and our column is CWDistance. df.loc[:,"CWDistance"]
#Now, let's say we only want to return the first 10 observations:
df.loc[:9,'CWDistance']

.iloc()
df.iloc[row_start : row_end, column_start, column_end]
.iloc() is integer based slicing, whereas .loc() used labels/column names.

Use just column_index. No Names

Here are some examples:

In [ ]:
df.iloc[:5]

In [ ]:
df.iloc[2:5,3:6]

In [ ]:
#df.iloc[1:5, ["Gender", "GenderGroup"]]# is error. column names can't be called with iloc. 
df.iloc[1:5, ]

We can view the data types of our data frame columns with by calling .dtypes on our data frame:

In [ ]:
df.dtypes

The output indicates we have integers, floats, and objects with our Data Frame.

We may also want to observe the different unique values within a specific column, lets do this for Gender:

In [ ]:
df.Height.unique()

In [ ]:
df.Gender.unique()

In [ ]:
df.GenderGroup.unique()

It seems that these fields may serve the same purpose, which is to specify male vs. female.

Lets check this quickly by observing only these two columns:

In [ ]:
df.loc[:,['Gender','GenderGroup']]

From eyeballing the output, it seems to check out.

We can streamline this by utilizing the groupby() and size() functions.

In [ ]:
df.groupby(['Gender','GenderGroup']).size()

This output indicates that we have two types of combinations.

Case 1: Gender = F & Gender Group = 1
Case 2: Gender = M & GenderGroup = 2.
This validates our initial assumption that these two fields essentially portray the same information.

In [ ]:
df[['Gender','GenderGroup']].value_counts()

In [ ]:
df.columns

In [ ]:
df[['Gender','GenderGroup','Glasses']].value_counts()

In [ ]:
df.groupby(['Gender','GenderGroup','Glasses']).size()

# **Data wrangling
We have the information of Canadian immigration form 1980 - 2013. We would like to analize the pattern of immigration to Canada from different countries.

For example, how is the patter of immigration from Japan to Canada during these years ?

The first thing we'll do is import two key data analysis modules: pandas and numpy.**

In [ ]:
import pandas as pd # primary data structure library
import numpy as np # useful for many scientific computing in Python

In [135]:
df = pd.read_excel('drive/MyDrive/Canada.xlsx',
                   sheet_name='Canada by Citizenship',
                   skiprows=range(20),
                   skipfooter=2,
                   engine='openpyxl'
                  )
df

Type    Coverage  \
0    Immigrants  Foreigners   
1    Immigrants  Foreigners   
2    Immigrants  Foreigners   
3    Immigrants  Foreigners   
4    Immigrants  Foreigners   
5    Immigrants  Foreigners   
6    Immigrants  Foreigners   
7    Immigrants  Foreigners   
8    Immigrants  Foreigners   
9    Immigrants  Foreigners   
10   Immigrants  Foreigners   
11   Immigrants  Foreigners   
12   Immigrants  Foreigners   
13   Immigrants  Foreigners   
14   Immigrants  Foreigners   
15   Immigrants  Foreigners   
16   Immigrants  Foreigners   
17   Immigrants  Foreigners   
18   Immigrants  Foreigners   
19   Immigrants  Foreigners   
20   Immigrants  Foreigners   
21   Immigrants  Foreigners   
22   Immigrants  Foreigners   
23   Immigrants  Foreigners   
24   Immigrants  Foreigners   
25   Immigrants  Foreigners   
26   Immigrants  Foreigners   
27   Immigrants  Foreigners   
28   Immigrants  Foreigners   
29   Immigrants  Foreigners   
30   Immigrants  Foreigners   
31   Immigrants  Foreigners   
32   Immigrants    Citizens   
33   Immigrants  Foreigners   
34   Immigrants  Foreigners   
35   Immigrants  Foreigners   
36   Immigrants  Foreigners   
37   Immigrants  Foreigners   
38   Immigrants  Foreigners   
39   Immigrants  Foreigners   
40   Immigrants  Foreigners   
41   Immigrants  Foreigners   
42   Immigrants  Foreigners   
43   Immigrants  Foreigners   
44   Immigrants  Foreigners   
45   Immigrants  Foreigners   
46   Immigrants  Foreigners   
47   Immigrants  Foreigners   
48   Immigrants  Foreigners   
49   Immigrants  Foreigners   
50   Immigrants  Foreigners   
51   Immigrants  Foreigners   
52   Immigrants  Foreigners   
53   Immigrants  Foreigners   
54   Immigrants  Foreigners   
55   Immigrants  Foreigners   
56   Immigrants  Foreigners   
57   Immigrants  Foreigners   
58   Immigrants  Foreigners   
59   Immigrants  Foreigners   
60   Immigrants  Foreigners   
61   Immigrants  Foreigners   
62   Immigrants  Foreigners   
63   Immigrants  Foreigners   
64   Immigrants  Foreigners   
65   Immigrants  Foreigners   
66   Immigrants  Foreigners   
67   Immigrants  Foreigners   
68   Immigrants  Foreigners   
69   Immigrants  Foreigners   
70   Immigrants  Foreigners   
71   Immigrants  Foreigners   
72   Immigrants  Foreigners   
73   Immigrants  Foreigners   
74   Immigrants  Foreigners   
75   Immigrants  Foreigners   
76   Immigrants  Foreigners   
77   Immigrants  Foreigners   
78   Immigrants  Foreigners   
79   Immigrants  Foreigners   
80   Immigrants  Foreigners   
81   Immigrants  Foreigners   
82   Immigrants  Foreigners   
83   Immigrants  Foreigners   
84   Immigrants  Foreigners   
85   Immigrants  Foreigners   
86   Immigrants  Foreigners   
87   Immigrants  Foreigners   
88   Immigrants  Foreigners   
89   Immigrants  Foreigners   
90   Immigrants  Foreigners   
91   Immigrants  Foreigners   
92   Immigrants  Foreigners   
93   Immigrants  Foreigners   
94   Immigrants  Foreigners   
95   Immigrants  Foreigners   
96   Immigrants  Foreigners   
97   Immigrants  Foreigners   
98   Immigrants  Foreigners   
99   Immigrants  Foreigners   
100  Immigrants  Foreigners   
101  Immigrants  Foreigners   
102  Immigrants  Foreigners   
103  Immigrants  Foreigners   
104  Immigrants  Foreigners   
105  Immigrants  Foreigners   
106  Immigrants  Foreigners   
107  Immigrants  Foreigners   
108  Immigrants  Foreigners   
109  Immigrants  Foreigners   
110  Immigrants  Foreigners   
111  Immigrants  Foreigners   
112  Immigrants  Foreigners   
113  Immigrants  Foreigners   
114  Immigrants  Foreigners   
115  Immigrants  Foreigners   
116  Immigrants  Foreigners   
117  Immigrants  Foreigners   
118  Immigrants  Foreigners   
119  Immigrants  Foreigners   
120  Immigrants  Foreigners   
121  Immigrants  Foreigners   
122  Immigrants  Foreigners   
123  Immigrants  Foreigners   
124  Immigrants  Foreigners   
125  Immigrants  Foreigners   
126  Immigrants  Foreigners   
127  Immigrants  Foreigners   
128  Immigra

In [137]:
df.tail()

Type    Coverage          OdName  AREA AreaName  REG  \
190  Immigrants  Foreigners        Viet Nam   935     Asia  920   
191  Immigrants  Foreigners  Western Sahara   903   Africa  912   
192  Immigrants  Foreigners           Yemen   935     Asia  922   
193  Immigrants  Foreigners          Zambia   903   Africa  910   
194  Immigrants  Foreigners        Zimbabwe   903   Africa  910   

                RegName  DEV             DevName  1980  1981  1982  1983  \
190  South-Eastern Asia  902  Developing regions  1191  1829  2162  3404   
191     Northern Africa  902  Developing regions     0     0     0     0   
192        Western Asia  902  Developing regions     1     2     1     6   
193      Eastern Africa  902  Developing regions    11    17    11     7   
194      Eastern Africa  902  Developing regions    72   114   102    44   

     1984  1985  1986  1987  1988  1989  1990  1991  1992  1993  1994  1995  \
190  7583  5907  2741  1406  1411  3004  3801  5870  5416  6547  5105  3723   
191     0     0     0     0     0     0     0     1     0     0     0     0   
192     0    18     7    12     7    18     4    18    41    41    39    73   
193    16     9    15    23    44    68    77    69    73    46    51    41   
194    32    29    43    68    99   187   129    94    61    72    78    58   

     1996  1997  1998  1999  2000  2001  2002  2003  2004  2005  2006  2007  \
190  2462  1752  1631  1419  1803  2117  2291  1713  1816  1852  3153  2574   
191     0     0     0     0     0     0     0     0     0     0     1     0   
192   144   121   141   134   122   181   171   113   124   161   140   122   
193    34    72    34    51    39    78    50    46    56    91    77    71   
194    39    44    43    49    98   110   191   669  1450   615   454   663   

     2008  2009  2010  2011  2012  2013  
190  1784  2171  1942  1723  1731  2112  
191     0     0     0     0     0     0  
192   133   128   211   160   174   217  
193    64    60   102    69    46    59  
194   611   508   494   434   437   407

In [136]:
pd.set_option("display.max_columns", None, #Allows all columns
              #"display.max_rows", 500      #Allows 500 rows 
             )
df

Type    Coverage  \
0    Immigrants  Foreigners   
1    Immigrants  Foreigners   
2    Immigrants  Foreigners   
3    Immigrants  Foreigners   
4    Immigrants  Foreigners   
5    Immigrants  Foreigners   
6    Immigrants  Foreigners   
7    Immigrants  Foreigners   
8    Immigrants  Foreigners   
9    Immigrants  Foreigners   
10   Immigrants  Foreigners   
11   Immigrants  Foreigners   
12   Immigrants  Foreigners   
13   Immigrants  Foreigners   
14   Immigrants  Foreigners   
15   Immigrants  Foreigners   
16   Immigrants  Foreigners   
17   Immigrants  Foreigners   
18   Immigrants  Foreigners   
19   Immigrants  Foreigners   
20   Immigrants  Foreigners   
21   Immigrants  Foreigners   
22   Immigrants  Foreigners   
23   Immigrants  Foreigners   
24   Immigrants  Foreigners   
25   Immigrants  Foreigners   
26   Immigrants  Foreigners   
27   Immigrants  Foreigners   
28   Immigrants  Foreigners   
29   Immigrants  Foreigners   
30   Immigrants  Foreigners   
31   Immigrants  Foreigners   
32   Immigrants    Citizens   
33   Immigrants  Foreigners   
34   Immigrants  Foreigners   
35   Immigrants  Foreigners   
36   Immigrants  Foreigners   
37   Immigrants  Foreigners   
38   Immigrants  Foreigners   
39   Immigrants  Foreigners   
40   Immigrants  Foreigners   
41   Immigrants  Foreigners   
42   Immigrants  Foreigners   
43   Immigrants  Foreigners   
44   Immigrants  Foreigners   
45   Immigrants  Foreigners   
46   Immigrants  Foreigners   
47   Immigrants  Foreigners   
48   Immigrants  Foreigners   
49   Immigrants  Foreigners   
50   Immigrants  Foreigners   
51   Immigrants  Foreigners   
52   Immigrants  Foreigners   
53   Immigrants  Foreigners   
54   Immigrants  Foreigners   
55   Immigrants  Foreigners   
56   Immigrants  Foreigners   
57   Immigrants  Foreigners   
58   Immigrants  Foreigners   
59   Immigrants  Foreigners   
60   Immigrants  Foreigners   
61   Immigrants  Foreigners   
62   Immigrants  Foreigners   
63   Immigrants  Foreigners   
64   Immigrants  Foreigners   
65   Immigrants  Foreigners   
66   Immigrants  Foreigners   
67   Immigrants  Foreigners   
68   Immigrants  Foreigners   
69   Immigrants  Foreigners   
70   Immigrants  Foreigners   
71   Immigrants  Foreigners   
72   Immigrants  Foreigners   
73   Immigrants  Foreigners   
74   Immigrants  Foreigners   
75   Immigrants  Foreigners   
76   Immigrants  Foreigners   
77   Immigrants  Foreigners   
78   Immigrants  Foreigners   
79   Immigrants  Foreigners   
80   Immigrants  Foreigners   
81   Immigrants  Foreigners   
82   Immigrants  Foreigners   
83   Immigrants  Foreigners   
84   Immigrants  Foreigners   
85   Immigrants  Foreigners   
86   Immigrants  Foreigners   
87   Immigrants  Foreigners   
88   Immigrants  Foreigners   
89   Immigrants  Foreigners   
90   Immigrants  Foreigners   
91   Immigrants  Foreigners   
92   Immigrants  Foreigners   
93   Immigrants  Foreigners   
94   Immigrants  Foreigners   
95   Immigrants  Foreigners   
96   Immigrants  Foreigners   
97   Immigrants  Foreigners   
98   Immigrants  Foreigners   
99   Immigrants  Foreigners   
100  Immigrants  Foreigners   
101  Immigrants  Foreigners   
102  Immigrants  Foreigners   
103  Immigrants  Foreigners   
104  Immigrants  Foreigners   
105  Immigrants  Foreigners   
106  Immigrants  Foreigners   
107  Immigrants  Foreigners   
108  Immigrants  Foreigners   
109  Immigrants  Foreigners   
110  Immigrants  Foreigners   
111  Immigrants  Foreigners   
112  Immigrants  Foreigners   
113  Immigrants  Foreigners   
114  Immigrants  Foreigners   
115  Immigrants  Foreigners   
116  Immigrants  Foreigners   
117  Immigrants  Foreigners   
118  Immigrants  Foreigners   
119  Immigrants  Foreigners   
120  Immigrants  Foreigners   
121  Immigrants  Foreigners   
122  Immigrants  Foreigners   
123  Immigrants  Foreigners   
124  Immigrants  Foreigners   
125  Immigrants  Foreigners   
126  Immigrants  Foreigners   
127  Immigrants  Foreigners   
128  Immigra

In [139]:

df.info(verbose=False)   #To start by getting basic information about your dataframe:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Columns: 43 entries, Type to 2013
dtypes: int64(37), object(6)
memory usage: 65.6+ KB


In [142]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 43 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Type      195 non-null    object
 1   Coverage  195 non-null    object
 2   OdName    195 non-null    object
 3   AREA      195 non-null    int64 
 4   AreaName  195 non-null    object
 5   REG       195 non-null    int64 
 6   RegName   195 non-null    object
 7   DEV       195 non-null    int64 
 8   DevName   195 non-null    object
 9   1980      195 non-null    int64 
 10  1981      195 non-null    int64 
 11  1982      195 non-null    int64 
 12  1983      195 non-null    int64 
 13  1984      195 non-null    int64 
 14  1985      195 non-null    int64 
 15  1986      195 non-null    int64 
 16  1987      195 non-null    int64 
 17  1988      195 non-null    int64 
 18  1989      195 non-null    int64 
 19  1990      195 non-null    int64 
 20  1991      195 non-null    int64 
 21  1992      195 no

In [144]:
df.shape

(195, 43)

In [145]:
df.columns

Index([    'Type', 'Coverage',   'OdName',     'AREA', 'AreaName',      'REG',
        'RegName',      'DEV',  'DevName',       1980,       1981,       1982,
             1983,       1984,       1985,       1986,       1987,       1988,
             1989,       1990,       1991,       1992,       1993,       1994,
             1995,       1996,       1997,       1998,       1999,       2000,
             2001,       2002,       2003,       2004,       2005,       2006,
             2007,       2008,       2009,       2010,       2011,       2012,
             2013],
      dtype='object')

In [146]:
df.index

RangeIndex(start=0, stop=195, step=1)

In [150]:
type(df.columns)
type(df.index)

pandas.core.indexes.range.RangeIndex

In [149]:
print(type(df.columns))
print(type(df.index))

<class 'pandas.core.indexes.base.Index'>
<class 'pandas.core.indexes.range.RangeIndex'>


In [152]:
type(df.columns)

pandas.core.indexes.base.Index

In [153]:
df.columns

Index([    'Type', 'Coverage',   'OdName',     'AREA', 'AreaName',      'REG',
        'RegName',      'DEV',  'DevName',       1980,       1981,       1982,
             1983,       1984,       1985,       1986,       1987,       1988,
             1989,       1990,       1991,       1992,       1993,       1994,
             1995,       1996,       1997,       1998,       1999,       2000,
             2001,       2002,       2003,       2004,       2005,       2006,
             2007,       2008,       2009,       2010,       2011,       2012,
             2013],
      dtype='object')

In [155]:
df.columns.tolist()

['Type',
 'Coverage',
 'OdName',
 'AREA',
 'AreaName',
 'REG',
 'RegName',
 'DEV',
 'DevName',
 1980,
 1981,
 1982,
 1983,
 1984,
 1985,
 1986,
 1987,
 1988,
 1989,
 1990,
 1991,
 1992,
 1993,
 1994,
 1995,
 1996,
 1997,
 1998,
 1999,
 2000,
 2001,
 2002,
 2003,
 2004,
 2005,
 2006,
 2007,
 2008,
 2009,
 2010,
 2011,
 2012,
 2013]

In [ ]:
df.index.tolist()

In [157]:

print(type(df.columns.tolist()))
print(type(df.index.tolist()))

<class 'list'>
<class 'list'>


In [158]:
type(df.columns.tolist())

list

In [159]:
type(df.index.tolist())

list

To view the dimensions of the dataframe, we use the shape instance variable of it.

Note: The main types stored in pandas objects are float, int, bool, datetime64[ns], datetime64[ns, tz], timedelta[ns], category, and object (string). In addition, these dtypes have item sizes, e.g. int64 and int32.

In pandas

axis = 0 ; The row (default) and

axis = 1 ; The columns

Let's clean the data set to remove a few unnecessary columns. We can use pandas drop() method as follows:

In [160]:
df.head(2)

Type    Coverage       OdName  AREA AreaName   REG          RegName  \
0  Immigrants  Foreigners  Afghanistan   935     Asia  5501    Southern Asia   
1  Immigrants  Foreigners      Albania   908   Europe   925  Southern Europe   

   DEV             DevName  1980  1981  1982  1983  1984  1985  1986  1987  \
0  902  Developing regions    16    39    39    47    71   340   496   741   
1  901   Developed regions     1     0     0     0     0     0     1     2   

   1988  1989  1990  1991  1992  1993  1994  1995  1996  1997  1998  1999  \
0   828  1076  1028  1378  1170   713   858  1537  2212  2555  1999  2395   
1     2     3     3    21    56    96    71    63   113   307   574  1264   

   2000  2001  2002  2003  2004  2005  2006  2007  2008  2009  2010  2011  \
0  3326  4067  3697  3479  2978  3436  3009  2652  2111  1746  1758  2203   
1  1816  1602  1021   853  1450  1223   856   702   560   716   561   539   

   2012  2013  
0  2635  2004  
1   620   603

Drop the columns that we are not interested, by:

In [161]:
favs = ['Type','Coverage','AREA','REG','DEV','DevName']

In [162]:
df.drop(favs,
        axis = 1, #Axis one is columns
        inplace = True)
df.head(2)

OdName AreaName          RegName  1980  1981  1982  1983  1984  1985  \
0  Afghanistan     Asia    Southern Asia    16    39    39    47    71   340   
1      Albania   Europe  Southern Europe     1     0     0     0     0     0   

   1986  1987  1988  1989  1990  1991  1992  1993  1994  1995  1996  1997  \
0   496   741   828  1076  1028  1378  1170   713   858  1537  2212  2555   
1     1     2     2     3     3    21    56    96    71    63   113   307   

   1998  1999  2000  2001  2002  2003  2004  2005  2006  2007  2008  2009  \
0  1999  2395  3326  4067  3697  3479  2978  3436  3009  2652  2111  1746   
1   574  1264  1816  1602  1021   853  1450  1223   856   702   560   716   

   2010  2011  2012  2013  
0  1758  2203  2635  2004  
1   561   539   620   603

Let's rename the columns so that they make sense.

We can use rename() method by passing in a dictionary of old and new names as follows:

In [163]:
new_names = {'OdName':'Country', 
            'AreaName':'Continent', 
            'RegName':'Region'
            }

type(new_names)

dict

In [164]:
df.rename(columns= new_names, 
          inplace=True       #replace the orginal df
         )
df.head(2)

Country Continent           Region  1980  1981  1982  1983  1984  1985  \
0  Afghanistan      Asia    Southern Asia    16    39    39    47    71   340   
1      Albania    Europe  Southern Europe     1     0     0     0     0     0   

   1986  1987  1988  1989  1990  1991  1992  1993  1994  1995  1996  1997  \
0   496   741   828  1076  1028  1378  1170   713   858  1537  2212  2555   
1     1     2     2     3     3    21    56    96    71    63   113   307   

   1998  1999  2000  2001  2002  2003  2004  2005  2006  2007  2008  2009  \
0  1999  2395  3326  4067  3697  3479  2978  3436  3009  2652  2111  1746   
1   574  1264  1816  1602  1021   853  1450  1223   856   702   560   716   

   2010  2011  2012  2013  
0  1758  2203  2635  2004  
1   561   539   620   603

In [165]:
new_name = {'Country':'País',
            'Continent':'Continente',
            'Region':'Región'}
df.rename(columns = new_name,
          inplace = True)
df.head(2)

País Continente           Región  1980  1981  1982  1983  1984  \
0  Afghanistan       Asia    Southern Asia    16    39    39    47    71   
1      Albania     Europe  Southern Europe     1     0     0     0     0   

   1985  1986  1987  1988  1989  1990  1991  1992  1993  1994  1995  1996  \
0   340   496   741   828  1076  1028  1378  1170   713   858  1537  2212   
1     0     1     2     2     3     3    21    56    96    71    63   113   

   1997  1998  1999  2000  2001  2002  2003  2004  2005  2006  2007  2008  \
0  2555  1999  2395  3326  4067  3697  3479  2978  3436  3009  2652  2111   
1   307   574  1264  1816  1602  1021   853  1450  1223   856   702   560   

   2009  2010  2011  2012  2013  
0  1746  1758  2203  2635  2004  
1   716   561   539   620   603